### ISSUE TITLE
JSONDecoder Errot after Passphrase

### ISSUE THREAD

**Issue by mariozupan** [jtyers/mutt-oauth2#1]
Is it the issue connected with python 3.11?

Traceback (most recent call last):
  File "/home/mario/Downloads/mutt_oauth2.py", line 107, in <module>
    token = json.loads(sub.stdout)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by jtyers** [comment]
This occurs because `pass` contains a value that is not valid JSON. You shouldn't create items in `pass` manually with this script, but rather call the script with `--authorize` and it will create the tokens in pass for you when it retrieves the oauth token. (At least, that's how it works if I remember...)

**Comment by mariozupan** [comment]
It happens when I try to: 
python mutt_oauth2.py my.token --authorize --verbose

**Comment by mariozupan** [comment]
What woud be the best gpg command for public key (my.token) export? You can try gpg --export some public key i.e. token and then authorized with mutt_oauth2.py to see if you get the same error. You mentioned pass app but I don't understand how pass is involved in these steps and how to prevent? Thanks in advance on your help.
